/** Barrel for the AI Extension feature. */
export {
  createAiApi,
  type AiApi,
  type EmbeddingFunctionRecord,
  type EmbeddingFunctionListResponse,
  type EmbedRequest,
  type EmbedResponse,
  type EmbedResponseDense,
  type EmbedResponseSparse,
  type RerankerFunctionRecord,
  type RerankerFunctionListResponse,
  type RerankRequest,
  type RerankResponse,
  type RerankCandidate,
  type RerankHit,
} from './api';
export {
  embeddingsListQueryKey,
  embeddingDetailQueryKey,
  rerankersListQueryKey,
  rerankerDetailQueryKey,
  useListEmbeddings,
  useEmbedding,
  useCreateEmbedding,
  useUpdateEmbedding,
  useDeleteEmbedding,
  useEmbed,
  useListRerankers,
  useReranker,
  useCreateReranker,
  useUpdateReranker,
  useDeleteReranker,
  useRerank,
  type UpdateEmbeddingVariables,
  type EmbedVariables,
  type UpdateRerankerVariables,
  type RerankVariables,
} from './hooks';
export {
  isDenseEmbedding,
  isSparseEmbedding,
  getEmbeddingDimension,
  getEmbeddingTag,
} from './utils';
