/** Barrel for the collections feature. */
export {
  createCollectionsApi,
  type CollectionsApi,
  type CollectionSummary,
  type CollectionListResponse,
  type CollectionListItem,
  type CollectionCreateRequest,
  type CollectionOpenRequest,
  type CollectionSchemaPayload,
  type FieldAddRequest,
  type FieldRenameRequest,
  type IndexCreateRequest,
  type ScalarIndexCreateRequest,
  type MaintenanceResponse,
  type RecentCollectionItem,
  type RecentCollectionListResponse,
  type RecentForgetRequest,
} from './api';
export {
  collectionsQueryKey,
  collectionDetailQueryKey,
  recentCollectionsQueryKey,
  useCollectionsList,
  useCollection,
  useCreateCollection,
  useOpenCollection,
  useCloseCollection,
  useFlushCollection,
  useOptimizeCollection,
  useDestroyCollection,
  useAddField,
  useDropField,
  useRenameField,
  useCreateIndex,
  useDropIndex,
  useCreateScalarIndex,
  useDropScalarIndex,
  useListRecent,
  useForgetRecent,
  useClearRecent,
  type AddFieldVariables,
  type DropFieldVariables,
  type RenameFieldVariables,
  type CreateIndexVariables,
  type DropIndexVariables,
  type CreateScalarIndexVariables,
  type DropScalarIndexVariables,
} from './hooks';
