/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe.
         */
        get: operations["healthz_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe.
         */
        get: operations["readyz_api_v1_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Collections
         * @description List collections currently **opened in this server process**.
         *
         *     The result is sourced from :class:`SdkBackend`'s in-memory registry, so
         *     every entry here represents a collection whose underlying SDK handle is
         *     live and ready to serve queries. Closing or destroying a collection
         *     removes it from this list immediately. For the persistent
         *     *recently opened* history (which survives process restarts) see
         *     :func:`list_recent` (``GET /collections/recent``).
         */
        get: operations["list_collections_api_v1_collections_get"];
        put?: never;
        /** Create Collection */
        post: operations["create_collection_api_v1_collections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Collection */
        post: operations["open_collection_api_v1_collections_open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recent
         * @description List recently opened collections (most-recent first, capped at 10).
         *
         *     Persisted to ``<data_dir>/config.json``; survives process restarts.
         *     Distinct from :func:`list_collections` which only reflects the **currently
         *     opened** in-memory set. Each entry is identified by absolute disk path
         *     and carries a ``lastOpenedAt`` ISO-8601 timestamp.
         */
        get: operations["list_recent_api_v1_collections_recent_get"];
        put?: never;
        post?: never;
        /**
         * Clear Recent
         * @description Drop every entry from the recent list. Idempotent.
         */
        delete: operations["clear_recent_api_v1_collections_recent_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/recent:forget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forget Recent
         * @description Remove a single path from the recent list.
         *
         *     Idempotent: a path that was never recorded still returns 204. The
         *     gateway resolves ``~`` and relative segments on the request side before
         *     matching against the canonical absolute paths kept on disk.
         */
        post: operations["forget_recent_api_v1_collections_recent_forget_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Collection
         * @description Standard *Get* (AIP-131) for a single opened collection.
         *
         *     Returns the aggregate :class:`CollectionSummary` (name, path, schema,
         *     stats) so detail-page clients can render everything in one round trip.
         *     Returns 404 ``COLLECTION_NOT_FOUND`` if the name is not currently opened
         *     in this process — callers can therefore use this endpoint as an
         *     existence/state probe. For partial reads (only ``schema`` or only
         *     ``stats``) prefer the dedicated sub-resource endpoints below.
         */
        get: operations["get_collection_api_v1_collections__name__get"];
        put?: never;
        post?: never;
        /** Close Collection */
        delete: operations["close_collection_api_v1_collections__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schema */
        get: operations["get_schema_api_v1_collections__name__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_v1_collections__name__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}:flush": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flush Collection */
        post: operations["flush_collection_api_v1_collections__name__flush_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}:optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optimize Collection */
        post: operations["optimize_collection_api_v1_collections__name__optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}:destroy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Destroy Collection */
        post: operations["destroy_collection_api_v1_collections__name__destroy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Field */
        post: operations["add_field_api_v1_collections__name__fields_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}/fields/{field}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Drop Field */
        delete: operations["drop_field_api_v1_collections__name__fields__field__delete"];
        options?: never;
        head?: never;
        /** Rename Field */
        patch: operations["rename_field_api_v1_collections__name__fields__field__patch"];
        trace?: never;
    };
    "/api/v1/collections/{name}/indexes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Index */
        post: operations["create_index_api_v1_collections__name__indexes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}/indexes/{vector_field}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Drop Index */
        delete: operations["drop_index_api_v1_collections__name__indexes__vector_field__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}/fields/{field}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Scalar Index */
        post: operations["create_scalar_index_api_v1_collections__name__fields__field__index_post"];
        /** Drop Scalar Index */
        delete: operations["drop_scalar_index_api_v1_collections__name__fields__field__index_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}/documents:browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Browse Documents
         * @description Filter Browser.
         *
         *     Returns up to ``limit`` rows that match ``filter`` (SQL-WHERE syntax,
         *     e.g. ``category = 'tech' AND year > 2020``). When the page is full we set
         *     ``truncated=true`` so the UI can prompt for a tighter filter.
         */
        post: operations["browse_documents_api_v1_collections__name__documents_browse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_collections__name__documents__doc_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_v1_collections__name__documents__doc_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Insert Documents */
        post: operations["insert_documents_api_v1_collections__name__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Documents
         * @description Partial update by ``id`` — omitted columns are preserved.
         *
         *     Each payload entry MUST carry an explicit ``id`` that already exists in
         *     the collection; only the keys present in the entry are mutated.
         */
        patch: operations["update_documents_api_v1_collections__name__documents_patch"];
        trace?: never;
    };
    "/api/v1/collections/{name}/documents:deleteBatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Documents */
        post: operations["delete_documents_api_v1_collections__name__documents_deleteBatch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}/documents:upsert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert Documents
         * @description Insert-or-update by ``id``.
         *
         *     Mirrors :meth:`zvec.Collection.upsert`: documents that already exist (by
         *     ``id``) are replaced; new ids are inserted. Auto-generated ULIDs are used
         *     for any payload missing an explicit id.
         */
        post: operations["upsert_documents_api_v1_collections__name__documents_upsert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}/documents:deleteByFilter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete By Filter */
        post: operations["delete_by_filter_api_v1_collections__name__documents_deleteByFilter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fs/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal In File Manager
         * @description Open the given path in the platform's file manager (Finder / Explorer / xdg-open).
         */
        post: operations["reveal_in_file_manager_api_v1_fs_reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fs/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Directory
         * @description List subdirectories of ``path`` (or ``$HOME`` when omitted).
         *
         *     Returns the resolved absolute path, parent path, and sorted entries.
         *     Files are intentionally excluded — the picker selects a directory only.
         */
        get: operations["list_directory_api_v1_fs_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{name}/searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description ANN search.
         *
         *     Metric is fixed at collection-create time on the per-vector ``indexParam``,
         *     so v0.2.0 no longer accepts a per-request override. ``filter`` is the raw
         *     Zvec SQL-WHERE expression (e.g. ``category = 'tech'``).
         *
         *     The body supports:
         *
         *     - ``queries`` — canonical multi-vector form with optional per-query
         *       ``id``, ``vector`` and index ``param`` (HNSW/IVF/HNSW_RABITQ/VAMANA).
         *     - ``vector`` (+ optional ``vectorField``) — legacy single-vector form,
         *       kept for backward compatibility.
         *     - ``rerankerName`` — references a reranker registered via
         *       ``POST /ai/rerankers``; the SDK applies it after ANN.
         */
        post: operations["search_api_v1_collections__name__searches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Embeddings */
        get: operations["list_embeddings_api_v1_ai_embeddings_get"];
        put?: never;
        /** Create Embedding */
        post: operations["create_embedding_api_v1_ai_embeddings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/embeddings/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Embedding */
        get: operations["get_embedding_api_v1_ai_embeddings__name__get"];
        /** Update Embedding */
        put: operations["update_embedding_api_v1_ai_embeddings__name__put"];
        post?: never;
        /** Delete Embedding */
        delete: operations["delete_embedding_api_v1_ai_embeddings__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/embeddings/{name}:embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Embed */
        post: operations["embed_api_v1_ai_embeddings__name__embed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/rerankers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rerankers */
        get: operations["list_rerankers_api_v1_ai_rerankers_get"];
        put?: never;
        /** Create Reranker */
        post: operations["create_reranker_api_v1_ai_rerankers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/rerankers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reranker */
        get: operations["get_reranker_api_v1_ai_rerankers__name__get"];
        /** Update Reranker */
        put: operations["update_reranker_api_v1_ai_rerankers__name__put"];
        post?: never;
        /** Delete Reranker */
        delete: operations["delete_reranker_api_v1_ai_rerankers__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/rerankers/{name}:rerank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rerank */
        post: operations["rerank_api_v1_ai_rerankers__name__rerank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BM25Config */
        BM25Config: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bm25";
            /** @default query */
            encodingType: components["schemas"]["EncodingType"];
            /** @default zh */
            language: components["schemas"]["BM25Language"];
            /**
             * B
             * @default 0.75
             */
            b: number;
            /**
             * K1
             * @default 1.2
             */
            k1: number;
        };
        /**
         * BM25Language
         * @enum {string}
         */
        BM25Language: "zh" | "en";
        /**
         * CollectionCreateRequest
         * @description Request body for ``POST /collections``.
         */
        CollectionCreateRequest: {
            /** Path */
            path: string;
            schema: components["schemas"]["CollectionSchema"];
        };
        /** CollectionListItem */
        CollectionListItem: {
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /** CollectionListResponse */
        CollectionListResponse: {
            /** Items */
            items: components["schemas"]["CollectionListItem"][];
        };
        /**
         * CollectionOpenRequest
         * @description Request body for ``POST /collections:open``.
         */
        CollectionOpenRequest: {
            /** Path */
            path: string;
        };
        /**
         * CollectionSchema
         * @description Top-level Collection schema (name + vectors + scalar fields).
         */
        CollectionSchema: {
            /** Name */
            name: string;
            /** Vectors */
            vectors?: components["schemas"]["VectorSchema"][];
            /** Fields */
            fields?: components["schemas"]["FieldSchema"][];
        };
        /**
         * CollectionStats
         * @description Stats returned by ``GET /collections/{name}/stats``.
         */
        CollectionStats: {
            /**
             * Documentcount
             * @default 0
             */
            documentCount: number;
            /**
             * Indexstate
             * @default none
             */
            indexState: string;
            /** Indexcompleteness */
            indexCompleteness?: {
                [key: string]: number;
            };
            /**
             * Storagebytes
             * @default 0
             */
            storageBytes: number;
        };
        /**
         * CollectionSummary
         * @description Detail payload for ``GET /collections/{name}``.
         */
        CollectionSummary: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            schema: components["schemas"]["CollectionSchema"];
            stats: components["schemas"]["CollectionStats"];
        };
        /** DefaultLocalDenseConfig */
        DefaultLocalDenseConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "default_local_dense";
            /**
             * Dimension
             * @default 384
             */
            dimension: number;
            /** @default huggingface */
            modelSource: components["schemas"]["ModelSource"];
            /** Device */
            device?: string | null;
            /**
             * Normalizeembeddings
             * @default true
             */
            normalizeEmbeddings: boolean;
            /**
             * Batchsize
             * @default 32
             */
            batchSize: number;
        };
        /** DefaultLocalRerankerConfig */
        DefaultLocalRerankerConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "default_local";
            /**
             * Modelname
             * @default cross-encoder/ms-marco-MiniLM-L6-v2
             */
            modelName: string;
            /** @default huggingface */
            modelSource: components["schemas"]["ModelSource"];
            /** Device */
            device?: string | null;
            /**
             * Batchsize
             * @default 32
             */
            batchSize: number;
        };
        /** DefaultLocalSparseConfig */
        DefaultLocalSparseConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "default_local_sparse";
            /** @default huggingface */
            modelSource: components["schemas"]["ModelSource"];
            /** Device */
            device?: string | null;
            /** @default query */
            encodingType: components["schemas"]["EncodingType"];
        };
        /** DocumentBatchDeleteRequest */
        DocumentBatchDeleteRequest: {
            /** Ids */
            ids: string[];
        };
        /** DocumentBatchDeleteResponse */
        DocumentBatchDeleteResponse: {
            /** Deleted */
            deleted: number;
        };
        /**
         * DocumentBrowseRequest
         * @description Body for ``POST /collections/{name}/documents:browse``.
         *
         *     Zvec 0.4.x has no ``list_all`` API, so we use a filtered ``query`` (without
         *     a vector) as the canonical browser. ``filter`` is the raw Zvec filter
         *     expression (``"category == 'tech' && publish_year > 2020"``); ``limit``
         *     caps the page size.
         */
        DocumentBrowseRequest: {
            /** Filter */
            filter?: string | null;
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /** Outputfields */
            outputFields?: string[] | null;
            /**
             * Includevector
             * @default false
             */
            includeVector: boolean;
        };
        /** DocumentBrowseResponse */
        DocumentBrowseResponse: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /**
         * DocumentDeleteByFilterRequest
         * @description Body for ``POST /collections/{name}/documents:deleteByFilter``.
         */
        DocumentDeleteByFilterRequest: {
            /**
             * Filter
             * @description SQL-WHERE filter (e.g. ``category = 'tech' AND year > 2020``).
             */
            filter: string;
        };
        /** DocumentDeleteByFilterResponse */
        DocumentDeleteByFilterResponse: {
            /** Deleted */
            deleted: number;
        };
        /**
         * DocumentInsertRequest
         * @description Body for ``POST /collections/{name}/documents``.
         */
        DocumentInsertRequest: {
            /** Documents */
            documents: {
                [key: string]: unknown;
            }[];
        };
        /** DocumentInsertResponse */
        DocumentInsertResponse: {
            /** Inserted */
            inserted: number;
            /** Ids */
            ids: string[];
        };
        /**
         * DocumentUpdateRequest
         * @description Body for ``PATCH /collections/{name}/documents``.
         *
         *     Zvec ``update`` performs **partial** updates: each document must carry
         *     an existing ``id`` plus the subset of scalar/vector columns to modify.
         *     Omitted columns retain their current values.
         */
        DocumentUpdateRequest: {
            /** Documents */
            documents: {
                [key: string]: unknown;
            }[];
        };
        /** DocumentUpdateResponse */
        DocumentUpdateResponse: {
            /** Updated */
            updated: number;
            /** Ids */
            ids: string[];
        };
        /**
         * DocumentUpsertRequest
         * @description Body for ``POST /collections/{name}/documents:upsert``.
         */
        DocumentUpsertRequest: {
            /** Documents */
            documents: {
                [key: string]: unknown;
            }[];
        };
        /** DocumentUpsertResponse */
        DocumentUpsertResponse: {
            /** Upserted */
            upserted: number;
            /** Ids */
            ids: string[];
        };
        /**
         * EmbedRequest
         * @description Body for ``POST /ai/embeddings/{name}:embed``.
         */
        EmbedRequest: {
            /** Texts */
            texts: string[];
            /**
             * Isquery
             * @description Whether to encode as query (vs. document); only meaningful for sparse / BM25 encoders that distinguish the two.
             * @default false
             */
            isQuery: boolean;
        };
        /** EmbedResponseDense */
        EmbedResponseDense: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "dense";
            /** Dimension */
            dimension: number;
            /** Vectors */
            vectors: number[][];
        };
        /** EmbedResponseSparse */
        EmbedResponseSparse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "sparse";
            /** Vectors */
            vectors: {
                [key: string]: number;
            }[];
        };
        /** EmbeddingFunctionListResponse */
        EmbeddingFunctionListResponse: {
            /** Items */
            items: components["schemas"]["EmbeddingFunctionRecord"][];
        };
        /**
         * EmbeddingFunctionRecord
         * @description Persisted embedding function (one row in ``ai_functions.json``).
         */
        EmbeddingFunctionRecord: {
            /**
             * Name
             * @description Unique embedding function name.
             */
            name: string;
            /** Description */
            description?: string | null;
            /** Config */
            config: components["schemas"]["DefaultLocalDenseConfig"] | components["schemas"]["DefaultLocalSparseConfig"] | components["schemas"]["BM25Config"] | components["schemas"]["QwenDenseConfig"] | components["schemas"]["QwenSparseConfig"] | components["schemas"]["OpenAIDenseConfig"];
        };
        /**
         * EncodingType
         * @description Encoding mode for sparse / BM25 encoders.
         * @enum {string}
         */
        EncodingType: "query" | "document";
        /**
         * FieldAddRequest
         * @description Body for ``POST /collections/{name}/fields`` — add a scalar field.
         */
        FieldAddRequest: {
            /** @description New scalar field definition. */
            field: components["schemas"]["FieldSchema"];
            /**
             * Expression
             * @description Optional Zvec expression used to backfill values for existing rows. Empty string defaults to the dtype's zero value.
             * @default
             */
            expression: string;
        };
        /**
         * FieldRenameRequest
         * @description Body for ``PATCH /collections/{name}/fields/{field}`` — rename only.
         */
        FieldRenameRequest: {
            /**
             * Newname
             * @description New scalar field name.
             */
            newName: string;
        };
        /**
         * FieldSchema
         * @description Definition of a single scalar field.
         */
        FieldSchema: {
            /**
             * Name
             * @description Field name (identifier-like)
             */
            name: string;
            /** @description Scalar data type */
            dataType: components["schemas"]["ScalarDataType"];
            /**
             * Nullable
             * @default false
             */
            nullable: boolean;
            /** @description Inverted index params; None means no index on this field. */
            indexParam?: components["schemas"]["ScalarIndexParam"] | null;
        };
        /**
         * FsEntry
         * @description A single subdirectory entry.
         */
        FsEntry: {
            /**
             * Name
             * @description Leaf name of the directory.
             */
            name: string;
            /**
             * Path
             * @description Absolute path of the directory.
             */
            path: string;
        };
        /**
         * FsListing
         * @description Directory listing returned to the picker UI.
         */
        FsListing: {
            /**
             * Path
             * @description Absolute path of the listed directory.
             */
            path: string;
            /**
             * Parent
             * @description Absolute path of the parent directory, or null at filesystem root.
             */
            parent?: string | null;
            /**
             * Home
             * @description The current user's home directory (absolute).
             */
            home: string;
            /**
             * Entries
             * @description Sorted subdirectories (excludes hidden entries by default).
             */
            entries?: components["schemas"]["FsEntry"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HnswQueryParamSpec
         * @description Maps to ``zvec.HnswQueryParam(ef, radius, is_linear, is_using_refiner)``.
         */
        HnswQueryParamSpec: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "HNSW";
            /**
             * Ef
             * @default 300
             */
            ef: number;
            /**
             * Radius
             * @default 0
             */
            radius: number;
            /**
             * Islinear
             * @default false
             */
            isLinear: boolean;
            /**
             * Isusingrefiner
             * @default false
             */
            isUsingRefiner: boolean;
        };
        /**
         * HnswRabitqQueryParamSpec
         * @description Maps to ``zvec.HnswRabitqQueryParam(ef, radius, is_linear, is_using_refiner)``.
         */
        HnswRabitqQueryParamSpec: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "HNSW_RABITQ";
            /**
             * Ef
             * @default 300
             */
            ef: number;
            /**
             * Radius
             * @default 0
             */
            radius: number;
            /**
             * Islinear
             * @default false
             */
            isLinear: boolean;
            /**
             * Isusingrefiner
             * @default false
             */
            isUsingRefiner: boolean;
        };
        /**
         * IndexCreateRequest
         * @description Body for ``POST /collections/{name}/indexes`` — (re)create a vector index.
         */
        IndexCreateRequest: {
            /**
             * Vectorfield
             * @description Name of the vector field.
             */
            vectorField: string;
            /** @default HNSW */
            indexType: components["schemas"]["IndexType"];
            /** @default COSINE */
            metric: components["schemas"]["MetricType"];
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /**
         * IndexType
         * @description Index families exposed by the Zvec SDK.
         * @enum {string}
         */
        IndexType: "HNSW" | "FLAT" | "IVF" | "HNSW_RABITQ" | "VAMANA" | "INVERT";
        /**
         * IvfQueryParamSpec
         * @description Maps to ``zvec.IVFQueryParam(nprobe)``.
         */
        IvfQueryParamSpec: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "IVF";
            /**
             * Nprobe
             * @default 10
             */
            nprobe: number;
        };
        /**
         * MaintenanceResponse
         * @description Generic response for ``flush`` / ``optimize`` operations.
         */
        MaintenanceResponse: {
            /**
             * Operation
             * @description Operation performed (``flush``, ``optimize``).
             */
            operation: string;
            /**
             * Timestamp
             * @description ISO-8601 timestamp when the operation finished.
             */
            timestamp: string;
        };
        /**
         * MetricType
         * @description Distance metrics accepted by the SDK.
         * @enum {string}
         */
        MetricType: "L2" | "IP" | "COSINE";
        /**
         * ModelSource
         * @description Where the local model weights are downloaded from.
         * @enum {string}
         */
        ModelSource: "huggingface" | "modelscope";
        /** OpenAIDenseConfig */
        OpenAIDenseConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "openai_dense";
            /**
             * Model
             * @default text-embedding-3-small
             */
            model: string;
            /** Dimension */
            dimension?: number | null;
            /** Apikey */
            apiKey?: string | null;
            /** Baseurl */
            baseUrl?: string | null;
        };
        /** QwenDenseConfig */
        QwenDenseConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "qwen_dense";
            /** Dimension */
            dimension: number;
            /**
             * Model
             * @default text-embedding-v4
             */
            model: string;
            /**
             * Apikey
             * @description DashScope API key. Stored in plain text; the registry file is chmod 0600.
             */
            apiKey?: string | null;
        };
        /** QwenRerankerConfig */
        QwenRerankerConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "qwen";
            /**
             * Model
             * @default gte-rerank-v2
             */
            model: string;
            /** Apikey */
            apiKey?: string | null;
        };
        /** QwenSparseConfig */
        QwenSparseConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "qwen_sparse";
            /** Dimension */
            dimension: number;
            /**
             * Model
             * @default text-embedding-v4
             */
            model: string;
            /** Apikey */
            apiKey?: string | null;
        };
        /**
         * RecentCollectionItem
         * @description One entry in the recently-opened-collections list.
         */
        RecentCollectionItem: {
            /**
             * Path
             * @description Absolute resolved disk path of the collection.
             */
            path: string;
            /**
             * Name
             * @description Collection name as stored in schema. May be null for legacy entries.
             */
            name?: string | null;
            /**
             * Lastopenedat
             * @description ISO-8601 UTC timestamp of when this path was last opened or created through the REST gateway.
             */
            lastOpenedAt: string;
        };
        /**
         * RecentCollectionListResponse
         * @description Response payload of ``GET /collections/recent``.
         */
        RecentCollectionListResponse: {
            /** Items */
            items: components["schemas"]["RecentCollectionItem"][];
        };
        /**
         * RecentForgetRequest
         * @description Body of ``POST /collections/recent:forget``.
         */
        RecentForgetRequest: {
            /**
             * Path
             * @description Path to drop from recents. The gateway resolves ``~`` and relative segments before matching.
             */
            path: string;
        };
        /**
         * RerankCandidate
         * @description One candidate fed into a cross-encoder / API reranker.
         */
        RerankCandidate: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /**
             * Score
             * @description Original ANN/BM25 score; ignored by cross-encoder rerankers.
             */
            score?: number | null;
        };
        /** RerankHit */
        RerankHit: {
            /** Id */
            id: string;
            /** Score */
            score: number;
            /** Text */
            text: string;
        };
        /**
         * RerankRequest
         * @description Body for ``POST /ai/rerankers/{name}:rerank``.
         */
        RerankRequest: {
            /**
             * Query
             * @description The user query string.
             */
            query: string;
            /** Candidates */
            candidates: components["schemas"]["RerankCandidate"][];
            /**
             * Topn
             * @default 10
             */
            topN: number;
        };
        /** RerankResponse */
        RerankResponse: {
            /** Results */
            results: components["schemas"]["RerankHit"][];
        };
        /** RerankerFunctionListResponse */
        RerankerFunctionListResponse: {
            /** Items */
            items: components["schemas"]["RerankerFunctionRecord"][];
        };
        /**
         * RerankerFunctionRecord
         * @description Persisted reranker function (one row in ``ai_functions.json``).
         */
        RerankerFunctionRecord: {
            /**
             * Name
             * @description Unique reranker function name.
             */
            name: string;
            /** Description */
            description?: string | null;
            /** Config */
            config: components["schemas"]["DefaultLocalRerankerConfig"] | components["schemas"]["QwenRerankerConfig"] | components["schemas"]["RrfRerankerConfig"] | components["schemas"]["WeightedRerankerConfig"];
        };
        /**
         * RerankerMetric
         * @description Metric used by :class:`zvec.WeightedReRanker` to fuse multi-vector scores.
         * @enum {string}
         */
        RerankerMetric: "L2" | "IP" | "COSINE";
        /**
         * RevealRequest
         * @description Request body for the reveal-in-file-manager endpoint.
         */
        RevealRequest: {
            /**
             * Path
             * @description Absolute path to reveal in the system file manager.
             */
            path: string;
        };
        /** RrfRerankerConfig */
        RrfRerankerConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "rrf";
            /**
             * Rankconstant
             * @default 60
             */
            rankConstant: number;
        };
        /**
         * ScalarDataType
         * @description Scalar field types supported in a Collection schema.
         * @enum {string}
         */
        ScalarDataType: "INT32" | "INT64" | "UINT32" | "UINT64" | "FLOAT" | "DOUBLE" | "BOOL" | "STRING" | "ARRAY_BOOL" | "ARRAY_INT32" | "ARRAY_INT64" | "ARRAY_UINT32" | "ARRAY_UINT64" | "ARRAY_FLOAT" | "ARRAY_DOUBLE" | "ARRAY_STRING";
        /**
         * ScalarIndexCreateRequest
         * @description Body for ``POST /collections/{name}/fields/{field}/index``.
         */
        ScalarIndexCreateRequest: {
            /**
             * Enablerangeoptimization
             * @default false
             */
            enableRangeOptimization: boolean;
            /**
             * Enableextendedwildcard
             * @default false
             */
            enableExtendedWildcard: boolean;
        };
        /**
         * ScalarIndexParam
         * @description Inverted index parameters attached to a scalar field.
         */
        ScalarIndexParam: {
            /** @default INVERT */
            indexType: components["schemas"]["IndexType"];
            /**
             * Enablerangeoptimization
             * @default false
             */
            enableRangeOptimization: boolean;
            /**
             * Enableextendedwildcard
             * @default false
             */
            enableExtendedWildcard: boolean;
        };
        /**
         * SearchRequest
         * @description Body for ``POST /collections/{name}/searches``.
         *
         *     The canonical form sets ``queries`` (1..8 ``VectorQuerySpec``). The legacy
         *     single-vector form (top-level ``vector`` + ``vectorField``) is still
         *     accepted for backward compatibility and is folded into ``queries[0]``.
         */
        SearchRequest: {
            /** Queries */
            queries?: components["schemas"]["VectorQuerySpec"][] | null;
            /** Vector */
            vector?: number[] | {
                [key: string]: number;
            } | null;
            /** Vectorfield */
            vectorField?: string | null;
            /**
             * Topk
             * @default 10
             */
            topK: number;
            /** Filter */
            filter?: string | null;
            /** Outputfields */
            outputFields?: string[] | null;
            /**
             * Includevector
             * @default false
             */
            includeVector: boolean;
            /**
             * Rerankername
             * @description Name of a registered reranker (see ``GET /ai/rerankers``). When set, the SDK applies the reranker after ANN.
             */
            rerankerName?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["SearchResult"][];
            /** Took Ms */
            took_ms: number;
            /** Traceid */
            traceId?: string | null;
        };
        /** SearchResult */
        SearchResult: {
            /** Id */
            id: string;
            /** Score */
            score: number;
            /** Fields */
            fields: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VamanaQueryParamSpec
         * @description Maps to ``zvec.VamanaQueryParam(ef_search, radius, is_linear, is_using_refiner)``.
         */
        VamanaQueryParamSpec: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "VAMANA";
            /**
             * Efsearch
             * @default 200
             */
            efSearch: number;
            /**
             * Radius
             * @default 0
             */
            radius: number;
            /**
             * Islinear
             * @default false
             */
            isLinear: boolean;
            /**
             * Isusingrefiner
             * @default false
             */
            isUsingRefiner: boolean;
        };
        /**
         * VectorDataType
         * @description Vector dtypes supported by the Zvec SDK.
         * @enum {string}
         */
        VectorDataType: "VECTOR_FP32" | "VECTOR_FP16" | "VECTOR_FP64" | "VECTOR_INT8" | "SPARSE_VECTOR_FP32" | "SPARSE_VECTOR_FP16";
        /**
         * VectorIndexParam
         * @description Index build parameters attached to a single vector field.
         */
        VectorIndexParam: {
            /** @default HNSW */
            indexType: components["schemas"]["IndexType"];
            /** @default COSINE */
            metric: components["schemas"]["MetricType"];
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /**
         * VectorQuerySpec
         * @description One ANN query targeting a single vector field.
         *
         *     Exactly one of ``id`` or ``vector`` must be supplied:
         *
         *     - ``id`` performs a "by-id" lookup — the SDK loads the stored vector for
         *       that document and uses it as the query vector.
         *     - ``vector`` supplies an explicit query vector.
         */
        VectorQuerySpec: {
            /**
             * Field
             * @description Target vector field name.
             */
            field: string;
            /**
             * Id
             * @description Existing document id; the stored vector is used as query.
             */
            id?: string | null;
            /**
             * Vector
             * @description Explicit query vector.
             */
            vector?: number[] | {
                [key: string]: number;
            } | null;
            /**
             * Param
             * @description Optional per-query index parameter (HNSW/IVF/HNSW_RABITQ/VAMANA).
             */
            param?: (components["schemas"]["HnswQueryParamSpec"] | components["schemas"]["IvfQueryParamSpec"] | components["schemas"]["HnswRabitqQueryParamSpec"] | components["schemas"]["VamanaQueryParamSpec"]) | null;
        };
        /**
         * VectorSchema
         * @description Definition of a vector field.
         */
        VectorSchema: {
            /** Name */
            name: string;
            dataType: components["schemas"]["VectorDataType"];
            /** Dimension */
            dimension: number;
            /** @description Optional index params; if omitted the index is created lazily. */
            indexParam?: components["schemas"]["VectorIndexParam"] | null;
        };
        /** WeightedRerankerConfig */
        WeightedRerankerConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "weighted";
            /** @default L2 */
            metric: components["schemas"]["RerankerMetric"];
            /** Weights */
            weights?: {
                [key: string]: number;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_api_v1_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_collections_api_v1_collections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionListResponse"];
                };
            };
        };
    };
    create_collection_api_v1_collections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_collection_api_v1_collections_open_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionOpenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recent_api_v1_collections_recent_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentCollectionListResponse"];
                };
            };
        };
    };
    clear_recent_api_v1_collections_recent_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forget_recent_api_v1_collections_recent_forget_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecentForgetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_api_v1_collections__name__get: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_collection_api_v1_collections__name__delete: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_api_v1_collections__name__schema_get: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_v1_collections__name__stats_get: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flush_collection_api_v1_collections__name__flush_post: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimize_collection_api_v1_collections__name__optimize_post: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    destroy_collection_api_v1_collections__name__destroy_post: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_field_api_v1_collections__name__fields_post: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drop_field_api_v1_collections__name__fields__field__delete: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
                field: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_field_api_v1_collections__name__fields__field__patch: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
                field: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_index_api_v1_collections__name__indexes_post: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drop_index_api_v1_collections__name__indexes__vector_field__delete: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
                vector_field: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scalar_index_api_v1_collections__name__fields__field__index_post: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
                field: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ScalarIndexCreateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drop_scalar_index_api_v1_collections__name__fields__field__index_delete: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
                field: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    browse_documents_api_v1_collections__name__documents_browse_post: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentBrowseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentBrowseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_collections__name__documents__doc_id__get: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_collections__name__documents__doc_id__delete: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insert_documents_api_v1_collections__name__documents_post: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentInsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentInsertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_documents_api_v1_collections__name__documents_patch: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_documents_api_v1_collections__name__documents_deleteBatch_post: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentBatchDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentBatchDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_documents_api_v1_collections__name__documents_upsert_post: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUpsertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_by_filter_api_v1_collections__name__documents_deleteByFilter_post: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentDeleteByFilterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDeleteByFilterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_in_file_manager_api_v1_fs_reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevealRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_directory_api_v1_fs_list_get: {
        parameters: {
            query?: {
                /** @description Absolute path to list. Defaults to the user's home. */
                path?: string | null;
                /** @description Include dotfile-prefixed entries when true. */
                show_hidden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FsListing"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_collections__name__searches_post: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_embeddings_api_v1_ai_embeddings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbeddingFunctionListResponse"];
                };
            };
        };
    };
    create_embedding_api_v1_ai_embeddings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbeddingFunctionRecord"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbeddingFunctionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_embedding_api_v1_ai_embeddings__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbeddingFunctionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_embedding_api_v1_ai_embeddings__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbeddingFunctionRecord"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbeddingFunctionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_embedding_api_v1_ai_embeddings__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    embed_api_v1_ai_embeddings__name__embed_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbedResponseDense"] | components["schemas"]["EmbedResponseSparse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rerankers_api_v1_ai_rerankers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RerankerFunctionListResponse"];
                };
            };
        };
    };
    create_reranker_api_v1_ai_rerankers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RerankerFunctionRecord"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RerankerFunctionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reranker_api_v1_ai_rerankers__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RerankerFunctionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_reranker_api_v1_ai_rerankers__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RerankerFunctionRecord"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RerankerFunctionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_reranker_api_v1_ai_rerankers__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerank_api_v1_ai_rerankers__name__rerank_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RerankRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RerankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
